apiVersion: v2
name: efk-stack
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: common
  version: 1.8.0
  repository: https://charts.bitnami.com/bitnami
- name: elasticsearch
  version: 17.0.0
  repository: https://charts.bitnami.com/bitnami
  condition: elasticsearch.enabled
- name: fluentd
  version: 4.1.6
  repository: https://charts.bitnami.com/bitnami
  condition: fluentd.enabled
- name: kibana
  version: 8.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: kibana.enabled
